go.mod
This removes a replace directive that was used earlier in the development of this packer builder. The `sshego` library is no longer used by the project so this can be safely removed.
=> Remove unused replace directive in go.mod file

builder/xenserver/common/step_type_boot_command.go
This is a bugfix for https://github.com/ddelnano/packer-plugin-xenserver/issues/12
Originally, this module connects to the cluster host master, instead of connecting to the host where the instance is. Ive tested it couple of times and it seems to be working.
=> Replace conn master host > instance host

docs/builders/xenserver-iso.html.markdown
This addresses #16 and will make it more clear that users can instruct packer to use a specific set of networks when creating a VM
=> Add documentation for the `network_names` configuration option

builder/xenserver/common/step_start_vm_paused.go, builder/xenserver/common/step_wait_for_ip.go, builder/xenserver/common/vm_cleanup.go, go.mod
This addresses #11.
```
ddelnano@ddelnano-desktop:~/go/src/github.com/xenserver/packer-builder-xenserver$  packer1.7 build  -debug  -
-var sr_name='Local storage' --var sr_iso_name=LocalISO examples/centos8.json
Debug mode enabled. Builds will not be parallelized.
xenserver-iso: output will be in this color.
==> xenserver-iso: XAPI client session established
==> xenserver-iso: Starting HTTP server on port 8000
==> xenserver-iso: Step: Create Instance
==> xenserver-iso: Using the following SR for the VM: OpaqueRef:10e7e21a-0569-4e6c-931e-d295a76a3be0
==> xenserver-iso: Created instance '8e9ae543-e7fb-0326-256b-6f9df5708377'
==> xenserver-iso: Step: Start VM Paused
==> xenserver-iso: Step: Set SSH address to VM host IP
==> xenserver-iso: Set host SSH address to '192.168.88.89'.
==> …
```
=> Ensure vm is cleaned up when build is interrupted on the wait for ip step

builder/xenserver/iso/builder.go, examples/http/ubuntu-2004/user-data, examples/ubuntu/ubuntu-2004.pkr.hcl
Rather than try to catch grub via VNC before it moves on, we can use the floppy_files mount to provide cloud-config by setting its volume label to `cidata`. This requires a hack in the cloud-config to prevent autoinstall from hanging at a prompt, but I think this is a fair trade for getting successful builds every time.
=> More reliable cloud-init startup

builder/xenserver/common/step_wait_for_ip.go
There seems to be some kind of scope mismatch here as the IP is correctly retrieved but seems to have been stashed in a shadowed variable. Here's a screencap of the issue in action:
Note that the IP is correct at ` Got IP '192.168.207.159' from XenServer tools` but then blank in `Got IP address ''`. This results in the connection never completing.
Here's a screencap after my patch showing the IP address shows in both log lines and the connection is established:
=> Fix XenServer tools guest IP address resolution

builder/xenserver/common/config.go, builder/xenserver/common/config.hcl2spec.go, builder/xenserver/common/step_start_vm_paused.go, builder/xenserver/iso/builder.go
I extracted the changes as-is from https://github.com/ddelnano/packer-plugin-xenserver/pull/28.
I needed to set the firmware to `uefi` because `bios` was not working properly when trying the build an Ubuntu 20.04 image. I had some weird issues when booting because `xenbus_probe_frontend` was timing out while waiting for devices to initialize. When using `uefi`, I don't have this problem and the Packer build completes in around 15 minutes instead of 27 minutes.
I'm not well-versed in Go, so let me know if something is missing such as tests or if you need more information from me.
I tested locally using:
```bash
go build -o packer-plugin-xenserver
chmod +x packer-plugin-xenserver
mv packer-plugin-xenserver \
/usr/local/bin/github.com/ddelnano/xenserver/packer-plugin-xenserver_v0.4.0_x5.0_dar …
```
=> feat: Make firmware configurable

builder/xenserver/iso/step_create_instance.go
Adds a line of code that should fix the issues decribed here on the [XCP-NG Forum](https://xcp-ng.org/forum/topic/6795/xo-packer-template-disk-issues/10)
The following fix calls the xapi `VM.remove_from_other_config` hook to remove any "disks" entries from the vm that will be turned into a template via Packer. Currently this fix has only been tested with the Xen Orchestra "Ubuntu Focal Fossa 20.04" default template.
=> Fix cloudinit ready template generation

.github/workflows/release.yml
It appears that the hashicorp's gpg agent github action collides with an agent github runs internally (see https://github.com/hashicorp/ghaction-import-gpg/issues/11 for more details). This switches the release job to what seems to be the best supported gpg agent action.
=> Remove hashicorps gpg github action to one that doesn't collide with Github's

README.md, examples/README.md, examples/ubuntu/ubuntu-2004.pkr.hcl
When Ubuntu releases a new ISO, they remove the previous URL. Unfortunately this URL is hardcoded in the packer HCL template and so the example requires frequent changes as upstream releases new minor releases.
This change takes advantage of the packer 1.8 `http` [data source](https://developer.hashicorp.com/packer/docs/datasources/http#body) and allows the example to dynamically discover the checksum and URL to use. This will ensure that the example always works, and will prevent friction when new users try out this packer plugin.
```
ddelnano@ddelnano-desktop:~/go/src/github.com/xenserver/packer-plugin-xenserver$ packer1.8 build examples/ubuntu/ubuntu-2004.pkr.hcl
xenserver-iso.ubuntu-2004: output will be in this color.
==> xenserver-iso.ubuntu-2004: XAPI client session established
==> …
```
=> Update the ubuntu example to be resilient to ISO releases

examples/README.md, examples/ubuntu/ubuntu-2004.pkr.hcl
Reverts ddelnano/packer-plugin-xenserver#54
The original change specified the Ubuntu version in multiple variables and needs to be refactored slightly. Reverting until that is addressed.
=> Revert "Update the ubuntu example to be resilient to ISO releases"

examples/ubuntu/ubuntu-2004.pkr.hcl
This is my second attempt at #54
=> Update ubuntu example to be resilient to upstream minor releases

builder/xenserver/common/common_config.go
This is a continuation of #42.
=> Allow ISO Storage repository to fallback to default SR if unspecified

builder/xenserver/common/client.go, builder/xenserver/common/common_config.go, builder/xenserver/common/config.go, builder/xenserver/common/config.hcl2spec.go, builder/xenserver/common/step_create_instance.go, builder/xenserver/xva/step_import_instance.go, docs/builders/iso/xenserver-iso.html.markdown
This is a continuation of #45 and must be rebased after #66 is merged.
=> Allow support for adding tags to VMs

docs/builders/iso/xenserver-iso.html.markdown
=> Add the firmware argument to the builder documentation since it was missing

builder/xenserver/common/common_config.go, builder/xenserver/iso/builder_test.go, builder/xenserver/xva/builder_test.go, docs/builders/iso/xenserver-iso.html.markdown, packer.json
This is a continuation of #82. The additional change included in this one is getting the tests to pass (they needed to be updated to test against the new default value)
=> Allow users to specify if xs tools should be managed by packer or not

builder/xenserver/common/common_config.go, docs/builders/iso/xenserver-iso.html.markdown, packer.json
I had some problem with the packer provider and Debian installation. Debian detect the tools ISO as a CD (it's logical, it's a CD) and try to parse it as a Debian disk. Obviously, that didn't work.
Since I found a way to install the tools with preseed (yeah it's ugly, but working):
```
d-i preseed/late_command string in-target wget https://github.com/xenserver/xe-guest-utilities/releases/download/v7.20.2/xe-guest-utilities_7.20.2-1_amd64.deb; in-target export RUNLEVEL=1; in-target dpkg -i xe-guest-utilities_7.20.2-1_amd64.deb`
```
and in your Ubuntu example, guest-tools are in the repo:
```
packages:
- xe-guest-utilities
```
I don't think plugging the ISO tools is needed anymore.
Other user who need to have tools can always plug it by setting `tools_iso_name = "guest-tools.iso"` in their …
=> Let user choose if they want tools or not.

builder/xenserver/common/config.go, builder/xenserver/common/config.hcl2spec.go, builder/xenserver/common/step_create_instance.go, builder/xenserver/iso/builder.go
Before this PR, the VDI name was hardcoded
With this PR, the user can set the name of the VDI.
Tested on my side:
```
uuid ( RO)                : 6121a165-1d0c-426e-9c9c-b16e5a928fbc
name-label ( RW): MyCustomeName-disk
name-description ( RW): 
sr-uuid ( RO): d0125395-80c1-663e-dd80-8315c990bc79
virtual-size ( RO): 21474836480
sharable ( RO): false
read-only ( RO): false
```
=> Allow user to set VDI name

builder/xenserver/common/common_config.go, builder/xenserver/common/config.hcl2spec.go, builder/xenserver/common/ssh.go, builder/xenserver/common/step_forward_port_over_ssh.go, builder/xenserver/common/step_set_vm_host_ssh_address.go, builder/xenserver/iso/builder_test.go, builder/xenserver/xva/builder_test.go, docs/builders/iso/xenserver-iso.html.markdown
This PR adds a Packer configuration option `remote_ssh_port` for Xen and XCP-ng primary servers that expose the SSH service on a port different than 22.
=> Add remote_ssh_port packer option

main.go, version/version.go
Summary: Fix plugin installation on 1.11.0 and later by fixing release version detection
This addresses #136 but will ensure that future releases don't need to be bumped. Setting the package level `version.Version` variable already existed in the [goreleaser configuration](https://github.com/ddelnano/packer-plugin-xenserver/blob/a776a46e1e600e0e854dfb8ac73aca876f8a8468/.goreleaser.yml#L32), but the variable was defined in the wrong package (`main.Version` instead of `version.Version`).
=> Fix plugin installation on 1.11.0 and later by fixing release version detection

builder/xenserver/common/common_config.go, builder/xenserver/common/config.hcl2spec.go, builder/xenserver/iso/builder.go, builder/xenserver/xva/builder.go, docs/builders/iso/xenserver-iso.html.markdown, examples/http/ubuntu-2404/user-data, examples/ubuntu/ubuntu-2404.pkr.hcl
At least the Ubuntu 24.04 server ISO hangs for 5 minutes when booting with a Xen-provided floppy drive. The primary purpose of floppy_files is to provide the autoinstall config files, and cloud-init is happy to find those files on an inserted CD instead. Add the ability for packer-plugin-xenserver to create such a CD.
=> Add support for `cd_files` in addition to `floppy_files`
